// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOpt3PhX--lKxlcQhI2npNgH20WRmUDUM',
    appId: '1:412251493918:web:b59aadf29fa836d626c00f',
    messagingSenderId: '412251493918',
    projectId: 'hostel-v3',
    authDomain: 'hostel-v3.firebaseapp.com',
    storageBucket: 'hostel-v3.firebasestorage.app',
    measurementId: 'G-LMDJ41NMJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLR34suc83zX-1UkHKme63q4c2mOZugiU',
    appId: '1:412251493918:android:50db71be64c034c826c00f',
    messagingSenderId: '412251493918',
    projectId: 'hostel-v3',
    storageBucket: 'hostel-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlrOxfyQxkC7uruSJQL1v8YMbTWAGOgGI',
    appId: '1:412251493918:ios:dca4d8dbebe2af0c26c00f',
    messagingSenderId: '412251493918',
    projectId: 'hostel-v3',
    storageBucket: 'hostel-v3.firebasestorage.app',
    iosBundleId: 'com.example.hostelv3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlrOxfyQxkC7uruSJQL1v8YMbTWAGOgGI',
    appId: '1:412251493918:ios:dca4d8dbebe2af0c26c00f',
    messagingSenderId: '412251493918',
    projectId: 'hostel-v3',
    storageBucket: 'hostel-v3.firebasestorage.app',
    iosBundleId: 'com.example.hostelv3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOpt3PhX--lKxlcQhI2npNgH20WRmUDUM',
    appId: '1:412251493918:web:157e378619586b3026c00f',
    messagingSenderId: '412251493918',
    projectId: 'hostel-v3',
    authDomain: 'hostel-v3.firebaseapp.com',
    storageBucket: 'hostel-v3.firebasestorage.app',
    measurementId: 'G-WB0BLGSHVT',
  );
}
