import 'package:flutter/material.dart';
import '../../models/mess_model.dart';
import '../../repositories/mess_repository.dart';

class MessManagementScreen extends StatefulWidget {
  const MessManagementScreen({super.key});

  @override
  State<MessManagementScreen> createState() => _MessManagementScreenState();
}

class _MessManagementScreenState extends State<MessManagementScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final _repository = MessRepository();

  // Menu Form Controllers
  final _breakfastController = TextEditingController();
  final _lunchController = TextEditingController();
  final _dinnerController = TextEditingController();
  DateTime _selectedDate = DateTime.now();
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _loadMenuForDate(_selectedDate);
  }

  Future<void> _loadMenuForDate(DateTime date) async {
    // In a real app we would query the detailed stream.
    // For simplicity, we just listen to the stream in the UI,
    // but here we might want to pre-fill the text fields if data exists.
    // Ideally, we'd wrap the Form in a StreamBuilder.
  }

  Future<void> _saveMenu() async {
    setState(() => _isLoading = true);
    try {
      final menu = MessMenu(
        id: '', // ID is generated by date in repo
        date: _selectedDate,
        breakfast: _breakfastController.text
            .split(',')
            .map((e) => e.trim())
            .toList(),
        lunch: _lunchController.text.split(',').map((e) => e.trim()).toList(),
        dinner: _dinnerController.text.split(',').map((e) => e.trim()).toList(),
      );

      await _repository.setMenu(menu);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Menu updated successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Mess Management'),
        backgroundColor: const Color(0xFF002244),
        foregroundColor: Colors.white,
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: Colors.white,
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white70,
          tabs: const [
            Tab(text: "Set Menu"),
            Tab(text: "Feedback & Analytics"),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [_buildMenuTab(), _buildAnalyticsTab()],
      ),
    );
  }

  Widget _buildMenuTab() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Date Picker
          Row(
            children: [
              Text(
                "Menu for: ${_selectedDate.toLocal().toString().split(' ')[0]}",
                style: const TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Spacer(),
              TextButton.icon(
                icon: const Icon(Icons.calendar_today),
                label: const Text("Change Date"),
                onPressed: () async {
                  final picked = await showDatePicker(
                    context: context,
                    initialDate: _selectedDate,
                    firstDate: DateTime.now().subtract(const Duration(days: 7)),
                    lastDate: DateTime.now().add(const Duration(days: 7)),
                  );
                  if (picked != null) {
                    setState(() => _selectedDate = picked);
                    // Important: Clear fields or re-fetch for new date
                    _breakfastController.clear();
                    _lunchController.clear();
                    _dinnerController.clear();
                  }
                },
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Using StreamBuilder to pre-fill if data exists
          StreamBuilder<MessMenu?>(
            stream: _repository.getMenuForDate(_selectedDate),
            builder: (context, snapshot) {
              if (snapshot.hasData && snapshot.data != null) {
                // This is a bit hacky for a text field, better to have proper state management
                // But for now, we only update if the controller is empty to avoid overwriting user typing
                if (_breakfastController.text.isEmpty) {
                  _breakfastController.text = snapshot.data!.breakfast.join(
                    ', ',
                  );
                }
                if (_lunchController.text.isEmpty) {
                  _lunchController.text = snapshot.data!.lunch.join(', ');
                }
                if (_dinnerController.text.isEmpty) {
                  _dinnerController.text = snapshot.data!.dinner.join(', ');
                }
              }

              return Column(
                children: [
                  _buildMealInput(
                    "Breakfast",
                    _breakfastController,
                    Icons.breakfast_dining,
                  ),
                  const SizedBox(height: 12),
                  _buildMealInput(
                    "Lunch",
                    _lunchController,
                    Icons.lunch_dining,
                  ),
                  const SizedBox(height: 12),
                  _buildMealInput(
                    "Dinner",
                    _dinnerController,
                    Icons.dinner_dining,
                  ),
                ],
              );
            },
          ),

          const SizedBox(height: 24),
          ElevatedButton(
            onPressed: _isLoading ? null : _saveMenu,
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF002244),
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 16),
            ),
            child: _isLoading
                ? const CircularProgressIndicator(color: Colors.white)
                : const Text("Publish Menu"),
          ),
          const SizedBox(height: 8),
          const Text(
            "Use comma to separate items (e.g., Rice, Dal, Curd)",
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.grey, fontSize: 12),
          ),
        ],
      ),
    );
  }

  Widget _buildMealInput(
    String label,
    TextEditingController controller,
    IconData icon,
  ) {
    return TextField(
      controller: controller,
      maxLines: 2,
      decoration: InputDecoration(
        labelText: label,
        prefixIcon: Icon(icon),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        filled: true,
        fillColor: Colors.grey[50],
      ),
    );
  }

  Widget _buildAnalyticsTab() {
    return StreamBuilder<List<MessFeedback>>(
      stream: _repository.getRecentFeedback(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }
        if (!snapshot.hasData || snapshot.data!.isEmpty) {
          return _buildEmptyAnalytics();
        }

        final feedbacks = snapshot.data!;
        double totalRating = 0;
        int breakfastCount = 0;
        int lunchCount = 0;
        int dinnerCount = 0;

        for (var f in feedbacks) {
          totalRating += f.rating;
          if (f.mealType == 'Breakfast') breakfastCount++;
          if (f.mealType == 'Lunch') lunchCount++;
          if (f.mealType == 'Dinner') dinnerCount++;
        }
        double avgRating = totalRating / feedbacks.length;

        return ListView(
          padding: const EdgeInsets.all(20),
          children: [
            _buildMainStats(avgRating, feedbacks.length),
            const SizedBox(height: 24),
            Row(
              children: [
                Expanded(
                  child: _buildSmallStatCard(
                    "Breakfast",
                    breakfastCount.toString(),
                    Icons.wb_sunny_outlined,
                    Colors.green,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: _buildSmallStatCard(
                    "Lunch",
                    lunchCount.toString(),
                    Icons.sunny,
                    Colors.orange,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: _buildSmallStatCard(
                    "Dinner",
                    dinnerCount.toString(),
                    Icons.nightlight_round,
                    Colors.deepPurple,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 32),
            const Text(
              "RECENT REVIEWS",
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.bold,
                color: Colors.grey,
                letterSpacing: 1.2,
              ),
            ),
            const SizedBox(height: 16),
            ...feedbacks.map((f) => _buildReviewCard(f)),
          ],
        );
      },
    );
  }

  Widget _buildEmptyAnalytics() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.analytics_outlined, size: 64, color: Colors.grey[300]),
          const SizedBox(height: 16),
          const Text(
            "No feedback analytics available",
            style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold),
          ),
        ],
      ),
    );
  }

  Widget _buildMainStats(double avg, int total) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFF002244), Color(0xFF004488)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(28),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF002244).withValues(alpha: 0.3),
            blurRadius: 15,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Column(
        children: [
          const Text(
            "Overall Satisfaction",
            style: TextStyle(color: Colors.white70, fontSize: 14),
          ),
          const SizedBox(height: 8),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.baseline,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Text(
                avg.toStringAsFixed(1),
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 48,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text(
                "/5.0",
                style: TextStyle(color: Colors.white38, fontSize: 18),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: List.generate(5, (index) {
              return Icon(
                index < avg.round()
                    ? Icons.star_rounded
                    : Icons.star_outline_rounded,
                color: Colors.orange,
                size: 28,
              );
            }),
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(20),
            ),
            child: Text(
              "Based on $total reviews",
              style: const TextStyle(color: Colors.white, fontSize: 12),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSmallStatCard(
    String label,
    String val,
    IconData icon,
    Color color,
  ) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.grey[100]!),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          Icon(icon, color: color, size: 20),
          const SizedBox(height: 8),
          Text(
            val,
            style: const TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Color(0xFF002244),
            ),
          ),
          Text(label, style: TextStyle(fontSize: 10, color: Colors.grey[500])),
        ],
      ),
    );
  }

  Widget _buildReviewCard(MessFeedback f) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.grey[100]!),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          CircleAvatar(
            radius: 20,
            backgroundColor: _getRatingColor(f.rating).withValues(alpha: 0.1),
            child: Text(
              f.rating.toString(),
              style: TextStyle(
                color: _getRatingColor(f.rating),
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      f.studentName,
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 14,
                        color: Color(0xFF002244),
                      ),
                    ),
                    Text(
                      "${f.date.day}/${f.date.month}",
                      style: TextStyle(color: Colors.grey[400], fontSize: 11),
                    ),
                  ],
                ),
                const SizedBox(height: 4),
                Text(
                  f.mealType,
                  style: TextStyle(
                    color: Colors.grey[500],
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  f.comment ?? "No comment provided",
                  style: const TextStyle(
                    fontSize: 14,
                    color: Color(0xFF002244),
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Color _getRatingColor(int rating) {
    if (rating >= 4) return Colors.green;
    if (rating >= 3) return Colors.orange;
    return Colors.red;
  }
}
