import 'package:flutter/material.dart';
import '../../models/mess_model.dart';
import '../../repositories/mess_repository.dart';

class MessManagementScreen extends StatefulWidget {
  const MessManagementScreen({super.key});

  @override
  State<MessManagementScreen> createState() => _MessManagementScreenState();
}

class _MessManagementScreenState extends State<MessManagementScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final _repository = MessRepository();

  // Menu Form Controllers
  final _breakfastController = TextEditingController();
  final _lunchController = TextEditingController();
  final _dinnerController = TextEditingController();
  DateTime _selectedDate = DateTime.now();
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _loadMenuForDate(_selectedDate);
  }

  Future<void> _loadMenuForDate(DateTime date) async {
    // In a real app we would query the detailed stream.
    // For simplicity, we just listen to the stream in the UI,
    // but here we might want to pre-fill the text fields if data exists.
    // Ideally, we'd wrap the Form in a StreamBuilder.
  }

  Future<void> _saveMenu() async {
    setState(() => _isLoading = true);
    try {
      final menu = MessMenu(
        id: '', // ID is generated by date in repo
        date: _selectedDate,
        breakfast: _breakfastController.text
            .split(',')
            .map((e) => e.trim())
            .toList(),
        lunch: _lunchController.text.split(',').map((e) => e.trim()).toList(),
        dinner: _dinnerController.text.split(',').map((e) => e.trim()).toList(),
      );

      await _repository.setMenu(menu);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Menu updated successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Mess Management'),
        backgroundColor: const Color(0xFF002244),
        foregroundColor: Colors.white,
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: Colors.white,
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white70,
          tabs: const [
            Tab(text: "Set Menu"),
            Tab(text: "Feedback & Analytics"),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [_buildMenuTab(), _buildAnalyticsTab()],
      ),
    );
  }

  Widget _buildMenuTab() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Date Picker
          Row(
            children: [
              Text(
                "Menu for: ${_selectedDate.toLocal().toString().split(' ')[0]}",
                style: const TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Spacer(),
              TextButton.icon(
                icon: const Icon(Icons.calendar_today),
                label: const Text("Change Date"),
                onPressed: () async {
                  final picked = await showDatePicker(
                    context: context,
                    initialDate: _selectedDate,
                    firstDate: DateTime.now().subtract(const Duration(days: 7)),
                    lastDate: DateTime.now().add(const Duration(days: 7)),
                  );
                  if (picked != null) {
                    setState(() => _selectedDate = picked);
                    // Important: Clear fields or re-fetch for new date
                    _breakfastController.clear();
                    _lunchController.clear();
                    _dinnerController.clear();
                  }
                },
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Using StreamBuilder to pre-fill if data exists
          StreamBuilder<MessMenu?>(
            stream: _repository.getMenuForDate(_selectedDate),
            builder: (context, snapshot) {
              if (snapshot.hasData && snapshot.data != null) {
                // This is a bit hacky for a text field, better to have proper state management
                // But for now, we only update if the controller is empty to avoid overwriting user typing
                if (_breakfastController.text.isEmpty) {
                  _breakfastController.text = snapshot.data!.breakfast.join(
                    ', ',
                  );
                }
                if (_lunchController.text.isEmpty) {
                  _lunchController.text = snapshot.data!.lunch.join(', ');
                }
                if (_dinnerController.text.isEmpty) {
                  _dinnerController.text = snapshot.data!.dinner.join(', ');
                }
              }

              return Column(
                children: [
                  _buildMealInput(
                    "Breakfast",
                    _breakfastController,
                    Icons.breakfast_dining,
                  ),
                  const SizedBox(height: 12),
                  _buildMealInput(
                    "Lunch",
                    _lunchController,
                    Icons.lunch_dining,
                  ),
                  const SizedBox(height: 12),
                  _buildMealInput(
                    "Dinner",
                    _dinnerController,
                    Icons.dinner_dining,
                  ),
                ],
              );
            },
          ),

          const SizedBox(height: 24),
          ElevatedButton(
            onPressed: _isLoading ? null : _saveMenu,
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF002244),
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 16),
            ),
            child: _isLoading
                ? const CircularProgressIndicator(color: Colors.white)
                : const Text("Publish Menu"),
          ),
          const SizedBox(height: 8),
          const Text(
            "Use comma to separate items (e.g., Rice, Dal, Curd)",
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.grey, fontSize: 12),
          ),
        ],
      ),
    );
  }

  Widget _buildMealInput(
    String label,
    TextEditingController controller,
    IconData icon,
  ) {
    return TextField(
      controller: controller,
      maxLines: 2,
      decoration: InputDecoration(
        labelText: label,
        prefixIcon: Icon(icon),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        filled: true,
        fillColor: Colors.grey[50],
      ),
    );
  }

  Widget _buildAnalyticsTab() {
    return StreamBuilder<List<MessFeedback>>(
      stream: _repository.getRecentFeedback(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }
        if (!snapshot.hasData || snapshot.data!.isEmpty) {
          return const Center(child: Text("No feedback received yet"));
        }

        final feedbacks = snapshot.data!;
        // Simple Average Calculation
        double totalRating = 0;
        for (var f in feedbacks) {
          totalRating += f.rating;
        }
        double avgRating = totalRating / feedbacks.length;

        return ListView(
          padding: const EdgeInsets.all(16),
          children: [
            // Summary Card
            Card(
              color: Colors.blue[50],
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  children: [
                    const Text(
                      "Average Quality Rating (Last 7 Days)",
                      style: TextStyle(fontSize: 14),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      avgRating.toStringAsFixed(1),
                      style: const TextStyle(
                        fontSize: 36,
                        fontWeight: FontWeight.bold,
                        color: Colors.blue,
                      ),
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: List.generate(5, (index) {
                        return Icon(
                          index < avgRating.round()
                              ? Icons.star
                              : Icons.star_border,
                          color: Colors.orange,
                        );
                      }),
                    ),
                    Text("${feedbacks.length} reviews"),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              "Recent Comments",
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            ...feedbacks.map(
              (f) => Card(
                margin: const EdgeInsets.only(bottom: 8),
                child: ListTile(
                  leading: CircleAvatar(
                    backgroundColor: _getRatingColor(f.rating),
                    child: Text(
                      f.rating.toString(),
                      style: const TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  title: Text(f.mealType),
                  subtitle: Text(f.comment ?? "No comment"),
                  trailing: Text(
                    "${f.date.day}/${f.date.month}",
                    style: TextStyle(color: Colors.grey[600], fontSize: 12),
                  ),
                ),
              ),
            ),
          ],
        );
      },
    );
  }

  Color _getRatingColor(int rating) {
    if (rating >= 4) return Colors.green;
    if (rating >= 3) return Colors.orange;
    return Colors.red;
  }
}
